### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by Jeremy1980** [remig/web_lic#1]
Please change Web Lic! => LDraw Instruction Creator

**Comment by remig** [comment]
For now, Web Lic can only import from LDraw, but it's straightforward to add support for importing other sources.  In other words, Web Lic isn't built on or strongly tied to LDraw.  Adding LDraw to the title doesn't make sense.  Also, 'Lic' isn't a acronym for anything anymore.  Once upon a time it may have meant something, but now it's just a proper noun 'Lic'.  The title is correct as is.
