### ISSUE TITLE
Line Weight / Thickness Setting

### ISSUE THREAD

**Issue by dephone** [remig/web_lic#10]
The stroke weight of the rendered images always stays constant. Independent of the CSI scale, output resolution (dpi) and page size. 

The lines come out a little too thin for printing. Would there be a way of adding a stroke weight option?

**Comment by remig** [comment]
Yeah, this is a known limitation of Lic.  Drawing nice thick lines with Open GL / HTML 5 canvas is hard, or at least it's beyond my limited 3D rendering skills.  I definitely want to fix this, I just don't know how.  If you or anyone else out there has any ideas on how to render thick lines here, I'd really appreciate the help.  All relevant 3D rendering logic is in [LDRender.js](https://github.com/remig/web_lic/blob/master/src/LDRender.js).

**Comment by dephone** [comment]
I have had a look around in the code and have forwarded it to some programmers that I know.
I found this from an earlier version of OpenGL? https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glLineWidth.xhtml perhaps could be utilised.

**Comment by remig** [comment]
Thanks, your last link helped a lot.  I pushed some changes that should draw nice thick lines even on high-res image export.  I didn't add UI to change the line thickness yet; I plan on adding that as part of a bigger 'customize 3D drawing' feature soon.

If you reload Lic, you should get version 0.41 (top right corner), which includes thicker edge lines.
