### ISSUE TITLE
Stud outlines (on black parts)

### ISSUE THREAD

**Issue by dephone** [remig/web_lic#14]
The white outlines on black parts are working fine although not displaying the vertical lines on studs correctly.
![screen shot 2018-11-27 at 14 20 37](https://user-images.githubusercontent.com/5230188/49084413-ac308800-f24f-11e8-8111-739879473ec6.png)

**Comment by remig** [comment]
I didn't forget about this one!  It was almost impossible to fix with the current 3D rendering logic I had, so I rewrote all of that.  It runs a lot faster now, and edges look better:

![4x6_nice_edges](https://user-images.githubusercontent.com/2846667/58361371-1151e880-7e43-11e9-90a2-dc6c8552de9e.png)

I'm finishing a last round of testing & bug fixing on this new rendering engine.  It should be public in the next few weeks.

**Comment by dephone** [comment]
Amazing , Remi – looking forward to using the new version on a project soon!
