### ISSUE TITLE
Step images don't show full model.

### ISSUE THREAD

**Issue by xolvox** [remig/web_lic#18]
I attempted to make a model and half of the model in the photos generated is completely cut off. Is there a way to view the rest of it? Or am I doing something wrong. I can provide photos if needed.

**Comment by remig** [comment]
The latest version of Lic (0.43) includes a couple new features to help fix this problem.  You can simply reload your browser page to get the latest version.

When you import a model, click 'Automatically shrink part images' to avoid clipping parts entirely from the start.

If you've already imported the model, try changing 'Edit -> 3D Part Rendering -> Camera Zoom'.  That will move the 3D scene's virtual camera further from the model, so more of it can fit in the image.  

If zooming out the camera leaves too much empty space around the model images, you can then scale the model images on the Template Page.

Let me know if that helps, or if there's still something else causing problems.
