### ISSUE TITLE
Hold structure

### ISSUE THREAD

**Issue by Jeremy1980** [remig/web_lic#2]
Can you put **style.css** and **icons.png** into css subdirectory ? Thanks.

**Comment by remig** [comment]
Right now, Web Lic is small enough and new enough that it doesn't need a build / compile / package step.  At some point soon, it will become complex enough that the added complexity of a build step will be worthwhile.  When that happens, I'll add a build step based on node & webpack, and I'll move stuff around as necessary.

**Comment by Jeremy1980** [comment]
Thanks for answer. I wish you and the project, all the best.
