### ISSUE TITLE
Add Rotation Icon in Version 0.47.0

### ISSUE THREAD

**Issue by Leowolf27** [remig/web_lic#29]
On version **0.47.0**

**--Observations--**
1. Upon re-opening the rotation dialog the _"Add Rotation Icon"_ will be checked regardless of whether or not the icon is present in the step.
2. If a rotation was previously applied, unchecking _"Add Rotation Icon"_ will reset the rotation of the model, without showing any changes to the values in the rotation dialog window. Upon clicking _"OK"_ the rotation is reset and the icon is removed. If the _"Custom Rotation"_ dialog is open once again, the rotation values are gone.
3. If you enter a rotation value on the dialog window and **then** uncheck the _"Add Rotation Icon"_, and click _"OK"_ the icon disappears without affecting the rotation.

If any of these are intended, please disregard.

**--Important!--**
- The icon can be properly removed without affecting the rotation by right clicking the whole "Step #" (example: Step 2) and selecting on the menu _"Delete Rotate Icon"_.
- And by clicking on the icon itself and selecting _"Delete Rotate Icon"_. (This does not resize the step image)

**--Notes--**
- Tested on Firefox.
- "Clear Cache" does not change the observations.
- The observations are true after applying preset rotations too.

Magnificent project, keep it alive!

**Comment by remig** [comment]
Thanks for the detailed bug report! I've fixed each of the problems you identified. Fix will be in the next version of Lic, coming in a few weeks.
