### ISSUE TITLE
Callout: Prepend Blank Step in Version 0.47.0

### ISSUE THREAD

**Issue by Leowolf27** [remig/web_lic#31]
On version 0.47.0

Create a Callout inside a Step.
Add Part(s) to the Callout.
Right click on the Callout and select Prepend Blank Step.

--Observations--
- Both Callout Steps remain as Step null.
- Part(s) cannot be moved to previous Callout Step null.
- Part(s) can only be added to original Callout Step.
- Same Part(s) can be added more than once to the same Callout Step.

If any of these are intended, please disregard.

--Important!--
- Append Blank Step on Callout works as expected.
- Using Append Blank Step (or Add Step) on Callout FIRST enumerates the Callout Steps (itself and previous).
- After the Callout Steps are enumerated Prepend Blank Step works as expected.
- Using Append Blank Step (or Add Step) on Callout AFTER using Prepend Blank Step will only enumerate the newly created Step counting all Steps present.
- Using Prepend Blank Step on Callout AGAIN AFTER a single Append Blank Step has been enumerated will create a Step null and reset the Append Blank Step to 1.
- Callout can only be deleted when having one empty step.

--Notes--

- Tested on Firefox.

Magnificent project, keep it alive!

**Comment by remig** [comment]
Thanks again for the great bug report! This is fixed now. Fix will be in the next version, coming out in the next few weeks.
