### ISSUE TITLE
Style buttons in text editing dialogs in Version 0.47.0

### ISSUE THREAD

**Issue by Leowolf27** [remig/web_lic#35]
On version 0.47.0

Select any editable text (like the title).
Open the "Change Text & Style..."

--Observations--

- The Bold button appears blue (what seems to be selected), regardless of the text original style.
- Moving the cursor over it will show the button highlight effect.
- Clicking on the Bold button changes its color to white and toggles the style on the text.
- At this point the Bold button no longer gets highlighted when the cursor is over it.
- Clicking anywhere else AFTER clicking the Bold button will revert the button color to blue, without affecting the style on the text, and the highlight effect returns to normal.

If any of these are intended, please disregard.

--Important!--

- The Italic style button shows a similar behavior, but does not change to blue when the style is applied. However, the highlight effect does get affected in a similar way.
- The behavior is true for annotation labels too.
- The behavior affects the side text editing dialog that appears when editing the template text.
- The side dialog shows text style changes in real time where as the dialog window does not.
- The Underline button in the side dialog is affected in a similar way to the Italic button, except that it doesn't toggle the effect on the text.
- The Underline button is not present in the dialog window, it is only in the side dialog.

--Notes--

- Tested on Firefox and Google Chrome.

Magnificent project, keep it alive!

**Comment by remig** [comment]
Thanks again for the detailed bug report. This is fixed; fix will be in the next version, coming out in the next few weeks.

Note that I've removed the 'Underline' buttons, at least for now. Implementing underline isn't very easy, and I don't think it's very useful. But if a few people ask for it, I'll add it.

**Comment by Leowolf27** [comment]
Hey no problem, I like to help where I can. 

Also, I have to agree with you, "underline" doesn't seem to be of much use, at least in this program.
