### ISSUE TITLE
Part imported as black - is showing as no color

### ISSUE THREAD

**Issue by zktech** [remig/web_lic#6]
I have two models with a black 1x3  Technic Beam - in them (32523.dat Technic Beam 3) from MLCad - LDraw.  They do not display and draw correctly. If I change the color in lic to dark grey they start to work correctly. I can then change the color back to black and all is well.  What could cause this issue.

**Comment by remig** [comment]
The problematic parts here were using LDraw's color code 24, which is the 'edge' color, and isn't really valid for parts in a model (it's only used for primitive, sub-parts).  I fixed this by treating such invalid colors as black, which is what most other LDraw programs do.

**Comment by zktech** [comment]
Cool thank you. 

Bryant Zimmerman 
 
Sr. Systems Architect
Grand Dial Communications, A ZK Tech Inc. Company
616-299-5607 (mobile) 
616-855-1030 Ext. 2003 (office)

----------------------------------------
