### ISSUE TITLE
Popup Dialog Missing 

### ISSUE THREAD

**Issue by zktech** [remig/web_lic#8]
After forcing a refresh to pull the latest version of lic I am having critical issues. 

When I right click on a step object and right click. I no longer get the scale or , customer rotate dialog boxes showing.  The export High Resolution dialog also does not appear.  My guess is there is something broke in the code that creates the dialog.   I am using the Chrome web browser on windows.  These were working prior to forcing the code pull from last night.

**Comment by remig** [comment]
Sorry, I can't reproduce this problem.  I've tried on a handful of machines, but they all work as expected.

In web Lic, could you save any existing work, then try 'File' -> 'Clear Cache' -> 'Everything', then reload the page entirely?  Please let me know if that helps or if you're still stuck.
